apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.9.11
    helm:
      values: |
        image:
          repository: ghcr.io/external-secrets/external-secrets
          tag: v0.9.11
        
        installCRDs: true
        
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        
        webhook:
          image:
            repository: ghcr.io/external-secrets/external-secrets
            tag: v0.9.11
          
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
        
        certController:
          image:
            repository: ghcr.io/external-secrets/external-secrets
            tag: v0.9.11
          
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
        
        serviceMonitor:
          enabled: true
          namespace: observability
        
        prometheus:
          enabled: true
          service:
            port: 8080
        
        rbac:
          create: true
        
        serviceAccount:
          create: true
          name: external-secrets
        
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          seccompProfile:
            type: RuntimeDefault
        
        podSecurityContext:
          fsGroup: 65534
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
