apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: 1.7.1
    helm:
      values: |
        tempo:
          repository: grafana/tempo
          tag: 2.3.1
          
          storage:
            trace:
              backend: local
              local:
                path: /var/tempo/traces
          
          receivers:
            jaeger:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:14250
                thrift_http:
                  endpoint: 0.0.0.0:14268
                thrift_compact:
                  endpoint: 0.0.0.0:6831
                thrift_binary:
                  endpoint: 0.0.0.0:6832
            zipkin:
              endpoint: 0.0.0.0:9411
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
            opencensus:
              endpoint: 0.0.0.0:55678
        
        persistence:
          enabled: true
          size: 10Gi
        
        serviceMonitor:
          enabled: true
        
        service:
          type: ClusterIP
          ports:
            - name: tempo-prom-metrics
              port: 3100
              targetPort: 3100
            - name: tempo-jaeger-thrift-compact
              port: 6831
              protocol: UDP
              targetPort: 6831
            - name: tempo-jaeger-thrift-binary
              port: 6832
              protocol: UDP
              targetPort: 6832
            - name: tempo-jaeger-thrift-http
              port: 14268
              protocol: TCP
              targetPort: 14268
            - name: tempo-jaeger-grpc
              port: 14250
              protocol: TCP
              targetPort: 14250
            - name: tempo-zipkin
              port: 9411
              protocol: TCP
              targetPort: 9411
            - name: tempo-otlp-legacy
              port: 55680
              protocol: TCP
              targetPort: 55680
            - name: tempo-otlp-http
              port: 4318
              protocol: TCP
              targetPort: 4318
            - name: tempo-otlp-grpc
              port: 4317
              protocol: TCP
              targetPort: 4317
            - name: tempo-opencensus
              port: 55678
              protocol: TCP
              targetPort: 55678
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true