apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://ot-container-kit.github.io/helm-charts/
    chart: redis-operator
    targetRevision: 0.15.10
    helm:
      values: |
        image:
          repository: quay.io/opstree/redis-operator
          tag: v0.15.0
          pullPolicy: IfNotPresent
        
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        
        serviceAccount:
          create: true
          name: redis-operator
        
        rbac:
          create: true
        
        nodeSelector: {}
        
        tolerations: []
        
        affinity: {}
        
        podSecurityContext:
          runAsNonRoot: true
          runAsUser: 1000
          fsGroup: 1000
        
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
              - ALL
        
        redisExporter:
          enabled: true
          image:
            repository: quay.io/opstree/redis-exporter
            tag: v1.44.0
            pullPolicy: IfNotPresent
        
        serviceMonitor:
          enabled: true
          namespace: observability
  destination:
    server: https://kubernetes.default.svc
    namespace: redis-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true