apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - scylladb-operator.yaml
  - scylladb-cluster.yaml
  - scylladb-monitoring.yaml

namespace: scylladb-system

commonLabels:
  app.kubernetes.io/name: scylladb
  app.kubernetes.io/part-of: heracles-services
