apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.26.1
    helm:
      values: |
        global:
          enabled: true
          tlsDisable: false
        
        server:
          image:
            repository: vault
            tag: 1.15.2
          
          standalone:
            enabled: false
          
          ha:
            enabled: true
            replicas: 3
            
            config: |
              ui = true
              
              listener "tcp" {
                tls_disable = 1
                address = "[::]:8200"
                cluster_address = "[::]:8201"
              }
              
              storage "file" {
                path = "/vault/data"
              }
              
              service_registration "kubernetes" {}
          
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - host: vault.ryone.dev
                paths:
                  - /
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            tls:
              - secretName: vault-tls
                hosts:
                  - vault.ryone.dev
          
          dataStorage:
            enabled: true
            size: 10Gi
            storageClass: null
            accessMode: ReadWriteOnce
          
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          
          extraEnvironmentVars:
            VAULT_CACERT: /vault/userconfig/vault-server-tls/ca.crt
            VAULT_TLSCERT: /vault/userconfig/vault-server-tls/tls.crt
            VAULT_TLSKEY: /vault/userconfig/vault-server-tls/tls.key
        
        ui:
          enabled: true
          serviceType: ClusterIP
        
        injector:
          enabled: true
          image:
            repository: hashicorp/vault-k8s
            tag: 1.4.0
          
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          
          metrics:
            enabled: true
        
        csi:
          enabled: true
          image:
            repository: hashicorp/vault-csi-provider
            tag: 1.4.1
          
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true