apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 5.41.4
    helm:
      values: |
        loki:
          auth_enabled: false
          
          commonConfig:
            replication_factor: 1
          
          storage:
            type: filesystem
          
          schemaConfig:
            configs:
              - from: 2020-10-24
                store: boltdb-shipper
                object_store: filesystem
                schema: v11
                index:
                  prefix: index_
                  period: 24h
          
          limits_config:
            enforce_metric_name: false
            reject_old_samples: true
            reject_old_samples_max_age: 168h
            max_cache_freshness_per_query: 10m
            split_queries_by_interval: 15m
          
          chunk_store_config:
            max_look_back_period: 0s
          
          table_manager:
            retention_deletes_enabled: false
            retention_period: 0s
        
        read:
          replicas: 1
        
        write:
          replicas: 1
        
        backend:
          replicas: 1
        
        gateway:
          enabled: true
          replicas: 1
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - host: loki.ryone.dev
                paths:
                  - path: /
                    pathType: Prefix
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
            tls:
              - secretName: loki-tls
                hosts:
                  - loki.ryone.dev
        
        monitoring:
          dashboards:
            enabled: true
          rules:
            enabled: true
          serviceMonitor:
            enabled: true
          lokiCanary:
            enabled: true
        
        test:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true