apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-operator
    targetRevision: 0.47.1
    helm:
      values: |
        manager:
          image:
            repository: ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator
            tag: 0.89.0
          
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
        
        admissionWebhooks:
          certManager:
            enabled: true
        
        kubeRBACProxy:
          enabled: true
          image:
            repository: gcr.io/kubebuilder/kube-rbac-proxy
            tag: v0.13.1
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
