apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-domain-cert
  namespace: cert-manager
spec:
  secretName: wildcard-domain-tls
  dnsNames:
    - "*.apps.heracles.ryone.dev"
  issuerRef:
    name: cloudflare-dns-issuer
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    size: 2048
  usages:
    - digital signature
    - key encipherment
