apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  version: "1.12.1"
  
  config:
    br-defaults:
      default-br-config: |
        clusterDefault:
          brokerClass: MTChannelBasedBroker
          apiVersion: v1
          kind: ConfigMap
          name: config-br-default-channel
          namespace: knative-eventing
        namespaceDefaults: {}
    
    br-default-channel:
      channel-template-spec: |
        apiVersion: messaging.knative.dev/v1
        kind: InMemoryChannel
    
    config-tracing:
      backend: jaeger
      jaeger-endpoint: http://tempo.observability.svc.cluster.local:14268/api/traces
      debug: "false"
      sample-rate: "0.1"
  
  high-availability:
    replicas: 2
  
  resources:
    - container: eventing-controller
      requests:
        cpu: 25m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 200Mi
    
    - container: eventing-webhook
      requests:
        cpu: 25m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 100Mi
