apiVersion: v1
kind: Namespace
metadata:
  name: kourier-system
  annotations:
    argocd.argoproj.io/sync-wave: "25"
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
  annotations:
    argocd.argoproj.io/sync-wave: "25"
spec:
  ingress:
    kourier:
      enabled: true
      service-type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-kourier
  namespace: knative-serving
  annotations:
    argocd.argoproj.io/sync-wave: "25"
data:
  _example: |
    enable-service-mesh: "false"
    enable-proxy-protocol: "false"
    cipher-suites: "ECDHE-ECDSA-AES256-GCM-SHA384,ECDHE-RSA-AES256-GCM-SHA384"
    ssl-protocols: "TLSv1.2,TLSv1.3"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kourier-ingress
  namespace: kourier-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    argocd.argoproj.io/sync-wave: "25"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "*.heracles.ryone.dev"
      secretName: knative-wildcard-tls
  rules:
    - host: "*.heracles.ryone.dev"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kourier
                port:
                  number: 80
